### PR TITLE
Add images to Mel Bolen.

### PR DESCRIPTION
**Pull request by trollmad3**
Added images to Mel Bolen.

### CODE REVIEW

**Comment by gemohandy** [comment]
As I mentioned on your last pull request, this one doesn't just need you to add the images in the folder already. We need more images of Mel Bolen's work, which _are not in the folder_. That's why I've sent Wayne to help you on a couple of occasions - if anyone can help you get more images for an artist, it's Wayne.

**Comment by gemohandy** [comment]
Also, you have some technical issues: the width attribute doesn't accept percentages, it only accepts pixels written as just a number. If you want a percentage for the width, use actual CSS, not the width attribute. As well, you can only have one element of a given ID per page. You should change the "slide" ID to a class so you can have multiple slides. And again: you _need to get more images from Wayne_. These three are _not enough_.

**Comment by trollmad3** [comment]
@gemohandy Do you want me to make a new pull request for this? I want to fix this issue today.

**Comment by gemohandy** [comment]
There's no need to make it a new pull request - as long as what you're doing is still within the scope of this (which is just adding images to the Mel Bolen gallery), it's perfectly fine.

**Comment by trollmad3** [comment]
@gemohandy Can I scale the image using GIMP? The `callout.jpg` image is way to big for the gallery.

**Comment by gemohandy** [comment]
@trollmad3 - Yeah, resizing the images is fine. In fact, it's probably better to resize them than to just alter their size via CSS - smaller images have faster loading times.

**Comment by gemohandy** [comment]
I'm not sure what the issue could be. Maybe there's some CSS somewhere that's sizing it, which is why resizing it doesn't work? As for the overlap, again, you might want to check with Kaitlin. She knows more about CSS and web design than I do.

**Comment by trollmad3** [comment]
@gemohandy I am going to close this pull request. I will create a new pull request when the issue is resolved.

**Pull request closed without merging**
