### PR TITLE
Fixed Multiple Low Priority

### LINKED ISSUE #221: Christine Shaw Header
The header of Christine Shaw's page covers parts of the rest of the page.

### PR DESCRIPTION
**Pull request by gemohandy**

### CODE REVIEW

**Comment by gemohandy** [comment]
When I first made this pull request, I did not intend for all four of the errors to be included. Only the first two commits were supposed to be in this pull request. However, it seems that Github has a mind of it's own. Thus, this pull request:
Fixed #221 
Fixed #217 
Fixed #207 
Fixed #201

**Comment by rye761** [comment]
Please ensure the header on the cshaw page is centered, it is currently off center. Also, please fix the line endings on jsures/style.css. Other than that this pull request looks great, but avoid fixing a plethora of issues in one pull request next time.

**Comment by gemohandy** [comment]
What do you mean by the line endings on JSures' CSS?

**Comment by gemohandy** [comment]
Okay, that seems to have actually made things worse. I am not sure I can fix it on this computer. Sorry!

**Comment by rye761** [comment]
Atom should be able to fix that for you. Just make sure your line endings are set to LF at the bottom of the screen.

**Comment by BmanDesignsCanada** [comment]
@rye761 I asked Bennett to do it as one pull request. They are low priority and usually very simple fixes. This is just easier rather than being flooded with pull requests. Any medium or high issues should be there own request though.

**Comment by BmanDesignsCanada** [comment]
Also this request should be renamed to fixes multiple low priority.

**Comment by gemohandy** [comment]
Okay, the errors with Travis all come from WMulcaster, a file that I got when syncing with the main repo. I have a new branch that has it fixed, but it is branched off of mine, as Atom doesn't show other people's forks. As such, it can't really be submitted until this whole problem is fixed. Are there any remaining problems with the errors I claim are fixed? I really don't know what to do about JSure.

**Pull request merged**
