### PR TITLE
Add missing photos

### PR DESCRIPTION
**Pull request by trollmad3**
#365  update photos.

### CODE REVIEW

**Comment by gemohandy** [comment]
Okay, this pull request cannot be merged as is - for some reason, it breaks the Build. I can’t figure out why, so I can’t ask you to fix it. However, there’s still your other two pull requests, neither of which can go through just yet - you need some images of Mel’s work before the gallery can be approved, and you should look into the other artist.json files to get a sense of the formatting they use and how you should format yours.

**Comment by gemohandy** [comment]
Actually, upon further examination, I have found the issue: you missed a comma. There needs to be a comma between each string in the change log array. You didn't put one between the last one that was there before, and the new one you added. You need to do that.

**Comment by trollmad3** [comment]
Alright.

**Comment by gemohandy** [comment]
This looks good. None of the tests are returning any more errors than before. I'm merging it.

**Pull request merged**
