### PR TITLE
Removed all Meta tags with name="city"

### PR DESCRIPTION
**Pull request by gemohandy**
@BmanDesignsCanada, you said we should probably do this, so I did. Two notes:
 - Due to concerns over ownership, reginabellringers.ca was not touched
 - Due to concerns over conflicts, JMitchell was not touched

### CODE REVIEW

**Comment by BmanDesignsCanada** [comment]
Please do reginabellringers and jmitchell. I sort out conflicts

**Comment by gemohandy** [comment]
Should I touch the o:SmartTagType things in ReginaBellRingers? I have no idea what they are.

**Comment by BmanDesignsCanada** [comment]
Only remove the meta tags with city

**Comment by gemohandy** [comment]
My main concern with the ReginaBellRingers was that they appeared when I searched 

> name="city"

in the repository. I don't think they actually have any meta tags with city as the name.

**Comment by BmanDesignsCanada** [comment]
Okay. if they don't have the meta tag nothing needs to be done.

**Pull request merged**
