### PR TITLE
Vicansky Image gallery

### PR DESCRIPTION
**Pull request by Aholicknight**
Created a slideshow per gallery.

### CODE REVIEW

**Comment by gemohandy** [comment]
Two things:
1. You missed a comma in the artist.json file. That's why it's not building.
2. The "master" branch this is based off of is _your_ master, which has fallen behind the official master. In particular, you have missed the spelling update, which changed pretty much every html file in the database. This includes VCicansky's index.html. I suspect that's why there are merge errors. I can manually clean them up, but I won't until we get a successful build from this branch.
...which I just realized won't happen, because one of the other things you missed was the change from caches to workspaces. The other tests won't run because the cache won't work for you. You'll need to figure out how to resolve the conflicts and update your branch yourself.

**Comment by trollmad3** [comment]
Fixed the conflict.

**Comment by trollmad3** [comment]
@synixebrett What do you mean its completely flattend?

**Comment by synixebrett** [comment]
Look at the changed files.

You are removing all of the previous lines, and adding them all back with everything not indented

**Comment by trollmad3** [comment]
@synixebrett So what would I do to fix this?

**Comment by synixebrett** [comment]
`It needs to be restored to how it was previously.`
You need to put the indentation back

**Comment by trollmad3** [comment]
@synixebrett Could I revert the changes then put back my changes?

**Comment by synixebrett** [comment]
Sure

**Comment by trollmad3** [comment]
Okay.

**Comment by trollmad3** [comment]
@synixebrett How would I restore everything to its pervious state?

**Comment by Aholicknight** [comment]
creating a new one, this pull request is far away from recovering.

**Pull request closed without merging**
