### PR TITLE
Scratch Not The Cat pictures

### PR DESCRIPTION
**Pull request by gemohandy**
Wayne asked me to make a blister for this. He needs some of these pictures on his site. I will elaborate in an issue.

### CODE REVIEW

**Comment by gemohandy** [comment]
I elaborated in #287

**Comment by BmanDesignsCanada** [comment]
We don't need or have space for 70 images. We will need to cut down the number being added.

**Comment by gemohandy** [comment]
@BmanDesignsCanada - We went through and removed all but 7 images. When are we commiting this so that someone can do stuff with them?

**Comment by gemohandy** [comment]
@synixebrett - could you take a look at this? All files modified by this commit follow the proper nomenclature, if I am not mistaken. If I am, can you let me know which file I need to fix? I'd prefer to clear up this pull request sooner rather than later.

**Comment by synixebrett** [comment]
Can you remove scratch_not_the_cat from the image names, then it will be good to merge

**Pull request merged**
